spring:
  data:
    redis:
      host: localhost
      port: 6380
  datasource:
    url: jdbc:mariadb://localhost:3306/drinkup
    username: test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  ai:
    openai:
      api-key: sk-SoyveCDj2hYGPPHj6cRzbuB4vCPZHPn6FiCqN1eNiUX6CGHZ
      base-url: https://chatapi.onechats.top
      embedding:
        enabled: true
        options:
          model: text-embedding-3-small
    zhipuai:
      api-key: 38c53e23e9ed4ffedbf57d1fdeeedaf6.NBSZeB5bDaFzISa4
      embedding:
        options:
          model: embedding-3
    vectorstore:
      milvus:
        initializeSchema: true
        client:
          host: localhost
          port: 19530
        databaseName: default
        collectionName: vector_store
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE